# permissions for end users to edit broadcastcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broadcastcronjob-editor-role
rules:
- apiGroups:
  - apps.kruise.io
  resources:
  - broadcastcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - broadcastcronjobs/status
  verbs:
  - get
